### PR TITLE
Raincatch 535 minor fixes

### PR DESCRIPTION
**Pull request by wtrocki**
Small fixes after reviewing code for RAINCATCH-539. As original PR was closed I added changes here. We need to rethink our build system to make sure that we can drop dist folder. I'm open to have it for the moment, but wanted to mark this as something we should address. 
Going to squash commits after. 

ping @nialldonnellyfh @witmicko @emilioicai

### CODE REVIEW

**Comment by nialldonnellyfh** [comment]
@wtrocki We can't drop the dist folder right now as there is a reference to it in the `lib/directive.js` file.

**Comment by wtrocki** [comment]
I think that we may just endup with single js file dist file and then we can ignore it. 
Reverting this changes. Are other changes ok? 

Can I also move dist folder to lib as it seems that now it's part of the code (despite being generated)?

**Comment by nialldonnellyfh** [comment]
@wtrocki I think we should do that as a separate JIRA for all of the modules instead of overloading these PRs, but I totally agree it should not be called dist any more.

**Comment by wtrocki** [comment]
@nialldonnellyfh Can we merge this documentation change?

**Comment by wtrocki** [comment]
Review anyone? Minor changes, but I think that they are important for this module

**Comment by emilioicai** [comment]
LGTM

**Review by emilioicai — APPROVED** [review]

**Pull request merged**
